### ISSUE TITLE
How to trigger nested validation?

### ISSUE THREAD

**Issue by geohuz** [jeffijoe/validx#3]
I have an Order class with nested Product class:
```
class Order {
   ...
   products:[],
   addProduct: action(()=> { this.producs.push(new Product(this))})
}
```

```
class Product {
   ...
   productName: '',
   validation: validationContext(),
   validate: action(()=>
        this.validation.reset().validate(this, {
            productName: [required({msg: 'required'})]
       })
   })
...
```

I'm wondering how can I fire up the validation in the product?

**Comment by jeffijoe** [comment]
Pretty straightforward, there's no real magic to it. In this example you're validating the order, as well as every product within it.

```js
class Order {
  @observable products = []

  validation = validationContext(this, {
    products: [
      ({ value }) => value.length > 0 || 'Please add at least 1 product',
      ({ value }) => value.every(p => p.validate()) || 'Not all products are valid'
    ]
  })
}

class Product {
  @observable productName = ''

  validation = validationContext(this, {
    productName: [required('Product name is required')]
  })

  @observable validate () {
    return this.validation.validate().isValid
  }
}
```

Since your rules are not dynamic, I hoisted the rules and context to the initialization.

Does this answer your question?

**Comment by geohuz** [comment]
My case is product being dynamically added into the order, so I figured out to validate in this way:
```
let errors = order.products.map(item=> {
   item.validate()
   return item.validation.errors
}
```

and I can check if there is any errors in the products array by using Ramda:
```
R.pipe(R.mergeAll, R.isEmpty)(errors)
```

**Comment by jeffijoe** [comment]
Yeah you can definitely do that. In fact, `validation.validate()` returns the context, so you can chain it: `item.validation.reset().validate().errors`

Can I close this?

**Comment by geohuz** [comment]
Thanks @jeffijoe ! I love validx!

**Comment by jeffijoe** [comment]
@geohuz glad you like it, tell your friends! 😄
